### ISSUE TITLE
md5 no se considera seguro para encriptar contraseñas

### ISSUE THREAD

**Issue by sriccisoft** [costaivan34/guia_gourmet_paw#12]
md5 ya no se considera como un algoritmo seguro  para el almacenamiento de contraseñas. Hoy en día existen algoritmos ["más resistentes"](https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html). PHP ofrece como parte de la API una [serie de funciones ](https://www.php.net/manual/es/ref.password.php) que permiten usar algunos de estos algoritmos más seguros. 

Este issue no está en la lista de pendientes, es solo a modo informativo.

**Comment by costaivan34** [comment]
Estuve mirando las recomendaciones que están en la página de php y cambie el algoritmo por password_hash para generar la contraseña y password_verify para recuperarla.
