### ISSUE TITLE
Revisar el uso de tags <section> y <article>

### ISSUE THREAD

**Issue by sriccisoft** [costaivan34/guia_gourmet_paw#15]
Tomemos por ejemplo el siguiente código:

https://github.com/costaivan34/guia_gourmet_paw/blob/1a88f343cf1dac7ba23558826c0d265185e9abe1/Applicacion/app/views/sitios/OneSitio.html#L17-L48

Cada restaurante es un `<article>`, lo cual es correcto debido a que lo podemos considerar un contenido "autocontenido" que es independiente en cierta forma del contexto de la página (es decir, lo saco del sitio y sigue siento un restaurante con determinadas características). Esto adhiere a la [especificación de HTML5 para dicho tag](https://html.spec.whatwg.org/multipage/sections.html#the-article-element). 

Ahora bien, si avanzamos un poco más en el código, vemos un sección "encabezado" que contiene otra secciones correspondientes a la galería de imágenes y más adelante a otra sección "contenedor" donde está el nombre del restaurante. Si miramos la [especificación de HTML5 para `<section>`](https://html.spec.whatwg.org/multipage/sections.html#the-section-element), vemos que nos dice que dicho elemento debe ser usado para un agrupamiento temático del contenido. En consecuencia:

- ¿Qué justificación tiene el uso de la sección "encabezado"?
- ¿La sección "contenedor" y la sección "fondo" no están siendo usadas más por una necesidad de presentación que semántica?

**Comment by costaivan34** [comment]
En este caso la seccion "encabezado" me quedó del diseño anterior y no cumple ninguna función por eso ahora no está presente. La sección "fondo" si esta por una necesidad de presentación, ¿Cómo podría modificarlo para prescindir de la sección y que tenga el mismo resultado en cuanto a la presentación?

**Comment by sriccisoft** [comment]
¿Por qué motivo no aplicas el fondo en el `<section>` padre?

**Comment by costaivan34** [comment]
Al final modifique el diseño para no utilizar ese section extra.
