### ISSUE TITLE
Formularios en general y de carga de restaurante en particular

### ISSUE THREAD

**Issue by tomasdelvechio** [costaivan34/guia_gourmet_paw#16]
Existe un problema en general con los formularios del sitio y en particular con el de carga de un sitio nuevo. Son varias cosas así que las voy listando por acá:

- No pueden todos los campos ser obligatorios. Cargar todo es bastante engorroso. Entiendo la dirección pues la ubicación en mapa es importante, pero teléfono y mail obligatorios? Y no hay opción de redes sociales?
- Me pasó que cargué todo el form con varios días y horarios, y cuando fui a mandar me rebotó el backend porque en la descripción había escrito poco texto. Por JS no me lo aviso, pero lo malo fue que perdí todos los días cargados y el lugar del mapa.
- Hablando de los días cargados, me parece que de todas las opciones posibles elegiste una poco dinámica y muy rígida. Entiendo lo de intentar dar la posibilidad de que cada día sea un horario diferente, pero en el esquema elegido se pierde por ejemplo la posibilidad de decir que el viernes esta abierto hasta las 2 AM (que ya seria sábado). Se me ocurren otras maneras que hubieran sido mas flexibles y menos engorrosas.

**Comment by costaivan34** [comment]
Modifiqué el formulario de Sitio, ahora los campos de teléfono y el mail no son obligatorios. Desde el principio del proyecto no existió la opción de redes sociales.
El script de JS y las verificaciones que hace el backend no estaban especificadas de la misma forma. Ahora el formulario se devuelve con más datos si ocurre un error.
Modifiqué la parte del horario y ahora es más flexible y permite armar horarios como el del ejemplo.
