### ISSUE TITLE
El directorio de SQL no es de migrations y no esta claro su contenido

### ISSUE THREAD

**Issue by tomasdelvechio** [costaivan34/guia_gourmet_paw#6]
La guía de instalación habla de *migrations*, pero los archivos del directorio `sql/` no son *migrations* ya que se editan en varios commits. 

Un esquema de *mgirations* crea nuevos archivos sql antes cada modificación del modelo, además de establecer un orden en los mismos para poder ejecutar todos los sql que me faltan (pensar si el proyecto ya está en producción, no se puede eliminar la base y crearla de nuevo por un cambio en el modelo (este orden puede ser a través de los nombres de los archivos o en un script).

Por otro lado, la propia guía habla de ejecutar los sql en orden, pero no se especifica en qué orden. O darle algún tipo de orden, o buscar otro esquema.

**Comment by costaivan34** [comment]
Modifiqué la guia explicando en que orden importar los archivos SQL y para que sirve cada uno. En realidad con un archivo se crea la estructura de la base de datos y con el otro se agregan algunos datos a las tablas. Creo que se aleja un poco del concepto de migrations pero la idea era tener un archivo que cargue todas las tablas y deje listo el sistema para pasar a produccion.

**Comment by tomasdelvechio** [comment]
> Modifiqué la guia explicando en que orden importar los archivos SQL y para que sirve cada uno. En realidad con un archivo se crea la estructura de la base de datos y con el otro se agregan algunos datos a las tablas. Creo que se aleja un poco del concepto de migrations pero la idea era tener un archivo que cargue todas las tablas y deje listo el sistema para pasar a produccion.

Perfecto si es así, pero que quede claro que eso no es migrations, es un script para generar la base inicial (no se puede actualizar una instalación previa existente). Si eso esta claro, perfecto.
