### ISSUE TITLE
Paquetes obsoletos

### ISSUE THREAD

**Issue by tomasdelvechio** [costaivan34/guia_gourmet_paw#7]
Por algún motivo, el paquete Twig está bloqueado a la rama 2.X, cuando ya existe una rama 3 para el mismo. Esto representa un potencial problema de seguridad, ya sea por el propio paquete como por la versión de PHP que obliga el mismo. Por ejemplo, la versión fijada no permite ser instalado con PHP 8 (Recordar que la 7.4 está por ser discontinuada en menos de 1 año: https://www.php.net/supported-versions.php).

Siempre mantener actualizados los paquetes de composer en la medida de lo posible.

Ojo, si se actualiza la versión de Twig, verificar si tiene retro-compatibilidad con la sintaxis de la versión 2. (miré medio rápido y parece ser idéntica)

**Comment by costaivan34** [comment]
Pude actualizar Twig a la version 3 y Monolog a la version 2. No pude actualizar la versión de PHP, ya que el hosting gratuito que estoy utlizando no permite una version superior a la 7.4, en los demas hosting que consulte, ocurre lo mismo.

**Comment by tomasdelvechio** [comment]
> Pude actualizar Twig a la version 3 y Monolog a la version 2. No pude actualizar la versión de PHP, ya que el hosting gratuito que estoy utlizando no permite una version superior a la 7.4, en los demas hosting que consulte, ocurre lo mismo.

7.4 esta técnicamente soportado aun, así que por el momento seria suficiente.
